//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowMgtSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoNumber
    {
        public string Reason { get; set; }
        public int Autonumber1 { get; set; }
        public string CompanyID { get; set; }
        public int Year { get; set; }
    }
}
