//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowMgtSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inquiry()
        {
            this.InquiryFiles = new HashSet<InquiryFile>();
        }
    
        public int InquiryID { get; set; }
        public int OrderID { get; set; }
        public int InquiryStatusID { get; set; }
        public int HandledBy { get; set; }
        public System.DateTime AllocatedDate { get; set; }
        public string Telephone { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> NextInqDate { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUserID { get; set; }
        public string InquiryName { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryFile> InquiryFiles { get; set; }
        public int InquiryIdx { get; set; }
    }
}
