//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowMgtSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InquiryFile
    {
        public int InquiryFileID { get; set; }
        public int InquiryID { get; set; }
        public string ImageName { get; set; }
        public string InquiryFileImage { get; set; }
    
        public virtual Inquiry Inquiry { get; set; }
    }
}
