//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowMgtSystem.Models
{
    using System;
    using System.Collections.Generic;
    using ViewModels;

    public partial class OrderSummery
    {
        public int OrderID { get; set; }
        public string OrderCode { get; set; }
        public int LocationID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime RegisteredDate { get; set; }
        public string OrderName { get; set; }
        public int ReferenceUserID { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUserID { get; set; }
        public Nullable<int> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int HandledByUserID { get; set; }
        public string LocationName { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string ReferenceUser { get; set; }
        public Nullable<int> InquiryID { get; set; }
        public Nullable<bool> InquiryStatus { get; set; }
        public Nullable<int> InquiryStatusID { get; set; }
        public string InquiryName { get; set; }
        public Nullable<int> HandledBy { get; set; }
        public string HandledByName { get; set; }
        public Nullable<System.DateTime> AllocatedDate { get; set; }
        public string Telephone { get; set; }
        public string InquiryRemark { get; set; }
        public Nullable<System.DateTime> NextInqDate { get; set; }
        public List<OrderSummerySume> orderSummerySume { get; set; }
        public int InquiryIdx { get; set; }
    }
}
